### ISSUE TITLE
SmartlingApiExample.py failing at utf16_test() 

### ISSUE THREAD

**Issue by TokyoBirdy** [Smartling/api-sdk-python#12]
Traceback (most recent call last):
  File "SmartlingApiExample.py", line 162, in <module>
    utf16_test()
  File "SmartlingApiExample.py", line 152, in utf16_test
    example.test()
  File "SmartlingApiExample.py", line 99, in test
    resp, code = self.fapi.upload(self.uploadData)
  File "/Users/ceciliahumlelu/smartling-api-sdk-python/smartlingApiSdk/SmartlingFileApi.py", line 56, in upload
    return self.commandUpload(uploadData)
  File "/Users/ceciliahumlelu/smartling-api-sdk-python/smartlingApiSdk/FileApiBase.py", line 116, in commandUpload
    return self.uploadMultipart(Uri.UPLOAD, params)
  File "/Users/ceciliahumlelu/smartling-api-sdk-python/smartlingApiSdk/FileApiBase.py", line 50, in uploadMultipart
    response_data, status_code = self.getHttpResponseAndStatus( uri, params, MultipartPostHandler)
  File "/Users/ceciliahumlelu/smartling-api-sdk-python/smartlingApiSdk/FileApiBase.py", line 77, in getHttpResponseAndStatus
    response = urllib2.urlopen(req)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    req = meth(req)
  File "/Users/ceciliahumlelu/smartling-api-sdk-python/smartlingApiSdk/MultipartPostHandler.py", line 58, in http_request
    boundary, data = self.multipart_encode(v_vars, v_files)
  File "/Users/ceciliahumlelu/smartling-api-sdk-python/smartlingApiSdk/MultipartPostHandler.py", line 85, in multipart_encode
    buffer += '\r\n' + fd.read().decode('utf-8') + '\r\n'
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 0: invalid start byte

**Comment by anatolija** [comment]
Can you provide xml document that fails to upload, please?

**Comment by junky** [comment]
Can't reproduce.
